### ISSUE TITLE
Code sucks

### ISSUE THREAD

**Issue by Mnpn03** [Mnpn03/MnpnBot-Rust#1]
Make code not suck with the help of jD91mZM2 and Rust.

**Comment by jD91mZM2** [comment]
Fixed with [2b102a](https://github.com/Mnpn03/MnpnBot-Rust/commit/2b102a3d97f322a495e0a6c4ec1e59ae10db20e8). To be fair the code wasn't that dirty at all. I mainly just moved all error handling to the `after` function, as well as removed a few `format`s (because format is *slightly* slower than using .push_str and .push).
